stages:
  - install-packages
  - validate
  - build
  - deploy

variables:
  IMAGE_NAME: "crazyfacka/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
  CONTAINER_NAME: ${CI_PROJECT_NAME}

install:
  stage: install-packages
  tags:
    - dev
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - node_modules/
    policy: push
  script:
    - echo "npm version $(npm --version)"
    - echo "node version $(node --version)"
    - npm i --verbose

lint:
  stage: validate
  tags:
    - dev
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run lint

test:
  stage: validate
  tags:
    - dev
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run test:unit

build-dev:
  stage: build
  tags:
    - dev
  except:
    - master
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build-dev
    - docker login -u crazyfacka -p ${DOCKER_HUB_PWD}
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

build:
  stage: build
  tags:
    - dev
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
    - docker login -u crazyfacka -p ${DOCKER_HUB_PWD}
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy-dev:
  stage: deploy
  tags:
    - dev
  except:
    - master
  script:
    - docker stop ${CONTAINER_NAME}-dev || true
    - docker rm -f ${CONTAINER_NAME}-dev || true
    - docker run -d -p 9001:80 --name ${CONTAINER_NAME}-dev $IMAGE_NAME

deploy-prd:
  stage: deploy
  tags:
    - dev
  only:
    - master
  script:
    - docker stop ${CONTAINER_NAME}-prd || true
    - docker rm -f ${CONTAINER_NAME}-prd || true
    - docker run -d -p 9000:80 --name ${CONTAINER_NAME}-prd $IMAGE_NAME